### PR TITLE
Fix wrong overlap check implementation

### LINKED ISSUE #535: Wrong overlap check implementation when create replica
Wrong overlap check implementation when create replica

### PR DESCRIPTION
**Pull request by zhangxu19830126**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #535 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

File: raftstore/store_handler.go [hunk 1]
```diff
@@ -159,21 +159,19 @@ func (s *store) tryToCreateReplicate(msg meta.RaftMessage) bool {
...
-				// Maybe split, but not registered yet.
-				s.cacheDroppedVoteMsg(msg.ShardID, msg)
-
-				s.logger.Info("replica has overlapped range",
-					s.storeField(),
-					log.ShardField("overlapped-replica", item),
-					log.ShardField("local-replica", p.getShard()))
-			}
+	// check range conflict
+	if conflictShard, ok := s.hasRangeConflict(msg.Group, msg.Start, msg.End); ok {
```
Comment (lni) [inline raftstore/store_handler.go:163]: change ok to conflict.

**Review by lni — APPROVED** [review]
